### ISSUE TITLE
对你的 KeepaliveConfig 配置，有什么作用

### ISSUE THREAD

**Issue by ForrestGumpForever** [dbfannin/ng2-keepalive#1]
对你的 KeepaliveConfig 配置，有什么作用？

**Comment by ForrestGumpForever** [comment]
具体 keep-alive 要怎么使用，能否给个demo?

**Comment by dbfannin** [comment]
@ForrestGumpForever, This module is no longer being supported. You are more than welcome to fork the project and build on top of it though.
