### ISSUE TITLE
ng2-keepalive/node_modules/@angular/http/src/backends/xhr_backend.js

### ISSUE THREAD

**Issue by ForrestGumpForever** [dbfannin/ng2-keepalive#3]
![image](https://user-images.githubusercontent.com/15998062/33250185-b008e9ac-d2f4-11e7-8efd-a5dc37a48236.png)

**Comment by dbfannin** [comment]
@ForrestGumpForever, This module is no longer being supported. You are more than welcome to fork the project and build on top of it though.
